#!/usr/bin/env python3
"""Writes src/moss/transcribe_unicode.inc: the Unicode letter (L*), number (N*)
and White_Space ranges the MOSS-Transcribe-Diarize byte-level BPE pre-tokenizer
needs to split text exactly like the Hugging Face Qwen2 tokenizer regex.
"""
from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "moss" / "transcribe_unicode.inc"
MAX_CODEPOINT = 0x10FFFF
RANGES_PER_LINE = 4
WHITE_SPACE = [(0x0009, 0x000D), (0x0020, 0x0020), (0x0085, 0x0085), (0x00A0, 0x00A0), (0x1680, 0x1680),
               (0x2000, 0x200A), (0x2028, 0x2029), (0x202F, 0x202F), (0x205F, 0x205F), (0x3000, 0x3000)]


def ranges_where(predicate) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for codepoint in range(MAX_CODEPOINT + 1):
        if not predicate(chr(codepoint)):
            continue
        if ranges and ranges[-1][1] == codepoint - 1:
            ranges[-1] = (ranges[-1][0], codepoint)
        else:
            ranges.append((codepoint, codepoint))
    return ranges


def category_ranges(prefix: str) -> list[tuple[int, int]]:
    return ranges_where(lambda ch: unicodedata.category(ch).startswith(prefix))


def table(name: str, ranges: list[tuple[int, int]]) -> str:
    cells = [f"{{0x{first:05X}, 0x{last:05X}}}" for first, last in ranges]
    lines = [", ".join(cells[i:i + RANGES_PER_LINE]) for i in range(0, len(cells), RANGES_PER_LINE)]
    body = ",\n    ".join(lines)
    return f"constexpr UnicodeRange {name}[] = {{\n    {body},\n}};\n"


def main() -> None:
    header = (f"// Generated by scripts/gen-moss-unicode-tables.py from Unicode {unicodedata.unidata_version}. "
              "Do not edit.\n\n")
    content = header + "\n".join([table("LETTER_RANGES", category_ranges("L")),
                                  table("NUMBER_RANGES", category_ranges("N")),
                                  table("WHITE_SPACE_RANGES", WHITE_SPACE)])
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
